CREATE DATABASE shopping_db;
USE shopping_db;
SHOW TABLES;
-- Q1. Total revenue generated by male vs female customers
SELECT
    Gender,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer_data
GROUP BY Gender;
-- Customers who used a discount but spent more than the average purchase amount
SELECT
    `Customer ID`,
    Gender,
    `Purchase Amount (USD)`
FROM customer_data
WHERE `Discount Applied` = 'Yes'
AND `Purchase Amount (USD)` >
(
    SELECT AVG(`Purchase Amount (USD)`)
    FROM customer_data
);

-- Top 5 products with the highest average review rating
SELECT
    `Item Purchased`,
    ROUND(AVG(`Review Rating`), 2) AS avg_rating
FROM customer_data
GROUP BY `Item Purchased`
ORDER BY avg_rating DESC
LIMIT 5;

-- Compare average purchase amount by shipping type

SELECT
    `Shipping Type`,
    ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_purchase
FROM customer_data
GROUP BY `Shipping Type`;

-- Compare subscribed vs non-subscribed customers
SELECT
    `Subscription Status`,
    ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_purchase,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer_data
GROUP BY `Subscription Status`;

-- Top 5 products with the highest percentage of discounted purchases
SELECT
    `Item Purchased`,
    ROUND(
        100 * SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer_data
GROUP BY `Item Purchased`
ORDER BY discount_percentage DESC
LIMIT 5;

-- Segment customers based on previous purchases
SELECT
    `Customer ID`,
    `Previous Purchases`,
    CASE
        WHEN `Previous Purchases` = 0 THEN 'New'
        WHEN `Previous Purchases` BETWEEN 1 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM customer_data;

-- Top 3 most purchased products within each category
SELECT
    Category,
    `Item Purchased`,
    total_purchases
FROM
(
    SELECT
        Category,
        `Item Purchased`,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY Category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer_data
    GROUP BY Category, `Item Purchased`
) AS ranked_products
WHERE rn <= 3
ORDER BY Category, total_purchases DESC;

-- Q9. Are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    `Subscription Status`,
    COUNT(*) AS total_customers
FROM customer_data
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;

-- Q10. Revenue contribution of each age group

SELECT
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;